language: objective-c
osx_image: xcode7
xcode_workspace: FeedHenry.xcworkspace
xcode_scheme: FeedHenry
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master


